//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DigiDental
{
    using System;
    using System.Collections.Generic;
    
    public partial class Clients
    {
        public string Client_HostName { get; set; }
        public string Client_IP { get; set; }
        public bool Client_IsVerify { get; set; }
        public string Agency_VerificationCode { get; set; }
        public System.DateTime UpdateTime { get; set; }
        public System.DateTime CreateTime { get; set; }
    }
}
